sudo: false
language: php
matrix:
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
  - php: 7
    env:
    - EXECUTE_CS_CHECK=true
    - EXECUTE_TEST_COVERALLS=true
  - php: hhvm
  - php: nightly
  - php: hhvm-nightly
  allow_failures:
  - php: 5.5
  - php: hhvm
  - php: nightly
  - php: hhvm-nightly
before_install:
- openssl aes-256-cbc -K $encrypted_aeb1b6d07a37_key -iv $encrypted_aeb1b6d07a37_iv
  -in deploy-key.enc -out deploy-key -d && chmod 600 deploy-key

- travis_retry composer install --no-interaction --ignore-platform-reqs
script:
- ./vendor/bin/phing build
after_script:
- if [ $TRAVIS_BRANCH == "master" ] && [ $EXECUTE_TEST_COVERALLS == 'true' ] ; then
  ./vendor/bin/phing deploy; fi
